### ISSUE TITLE
Watch directories but not the files in them?

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#16]
This request came from https://code.google.com/p/go/issues/detail?id=7788.

> my use-case regards watching some folders and know if anything changed inside them, but not caring for the single files.

I don't know if it's possible to do this, especially across every OS, but an interesting request.

**Comment by arp242** [comment]
Given that this was as single feature request from 8 years ago and that no one else asked for it since, I'll close this for now, especially since it seems hard to implement in a cross-platform way. If there are more people who really want it we can always add it later, but I see little point in keeping an issue open for it now.
