### ISSUE TITLE
Test hangs with gccgo

### ISSUE THREAD

**Issue by NightTsarina** [fsnotify/fsnotify#190]
### Which operating system (GOOS) and version are you using?
```
$ uname -a
Linux zelenka 3.16.0-4-s390x #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) s390x GNU/Linux
$ go version
go version go1.6.1 gccgo (Debian 6.2.1-5) 6.2.1 20161124 linux/s390x
```

### Please describe the issue that occurred.

I noticed a package using fsnotify (prometheus) is failing to build in s390x, because a test hangs forever. I tried running fsnotify tests there, and I see similar behaviour: the `TestRemoveWithClose` test hangs with high CPU usage. `strace` shows loads of useless select calls:

```
[pid 21646] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid 21646] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid 21646] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
```

I tried this also on amd64/gccgo with the same results. I'm including a full strace of the failing test in case it helps: [out.txt](https://github.com/fsnotify/fsnotify/files/624782/out.txt)

**Comment by nathany** [comment]
Thanks for reporting the issue.

I've not tested fsnotify with gccgo yet, nor do we have it set up in CI. That would be a good idea.

**Comment by arp242** [comment]
I tried to reproduce this to see if it's still happening, but my system's package manager has GCC 10.2, which corresponds to Go 1.15 and this library needs Go 1.16 :-/

If I test with v1.4.9 I get:

    [~cg/fsnotify](tags/v1.4.9)% ~/gccgo/go test .
    unable to allocate additional stack space: errno 22
    FAIL    github.com/fsnotify/fsnotify    0.089s

Which is a rather odd error, and seems related to some gccgo bug/thing rather than this package, as it also happens for other packages:

    [~cg/toml](master)% ~/gccgo/go test .
    unable to allocate additional stack space: errno 22
    FAIL    github.com/BurntSushi/toml      0.087s

That package is just some TOML parsing; no "advanced" syscall usage or anything.

I know it's been years @NightTsarina, but can you still reproduce this?
