### ISSUE TITLE
Google bot for CLA checking

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#193]
Though the fsnotify project doesn't currently have maintainers who are Google employees, the license and CLA are still needed.

* The code fsnotify is based on was in the Go standard library pre-1.0 and was moved to the x/exp sub-repository before Chris Howey created fsnotify. So it was under Google license from the start.
* There has been the occasional talk of utilizing fsnotify in the godoc tool or even the go tool (to speed up compilation). The core Go codebase legally [cannot vendor code not covered by the Google CLA](https://github.com/golang/go/issues/17244#issuecomment-254290929).

It would be nice to automate the CLA process so that it isn't forgotten. Google already has an official bot for CLA checking, what would it take to set it up? @willnorris

This should apply to fsnotify proper, as well as other repositories being worked on within the fsnotify organization, as they are intended to become dependencies of fsnotify (other than fsnotify.org).

Some administrative effort may also be needed to ensure none of the existing contributions have gone in without the CLA in the past. https://github.com/howeyc/fsnotify/issues/85

**Comment by willnorris** [comment]
The CLA is an agreement between the contributor and the project maintainer.  Since Google is neither of those, we wouldn't actually be party to the agreement, so I'm not sure that using the Google CLA makes sense.

The discussion in golang/go#17244 is interesting, and I'll have to talk with some folks next week to better understand the situation and what we can do in cases like this.  Feel free to ping me if you don't hear back in a while.

**Comment by nathany** [comment]
Thanks @willnorris.

The licensing and CLA has felt awkward to me for a long time (#119). Let me confirm if the Go team still has any plans to use fsnotify in core. I'll post to the golang-dev mailing list and drop a link here.

What would need to change for Google to be the project maintainer? If there were some Google employees maintaining fsnotify, would that be sufficient? I'm happy to pass over the reigns to make it work.

**Comment by nathany** [comment]
Using fsnotify in core, license and CLA 
https://groups.google.com/forum/#!topic/golang-dev/UwNizs08YD0

**Comment by nathany** [comment]
@willnorris I would really like to sort out the licensing issue. Thanks.
https://groups.google.com/forum/#!topic/golang-dev/UwNizs08YD0

**Comment by nathany** [comment]
@bradfitz suggests doing something similar to Camlistore. From https://github.com/camlistore/go4/#details:

> CLA compliant contributors must agree to the Google CLA (the same as Go itself). This ensures we can move things into Go as necessary in the future. It also makes lawyers at various companies happy. The CLA is not a copyright assignment; you retain the copyright on your work. The CLA just says that your work is open source and you have permission to open source it. See https://golang.org/doc/contribute.html#tmp_6

Here are the instructions from @willnorris. I suspect we will want the CLA checking for the whole organization, including fsevents or any new repos created. The fsnotify.org website doesn't really need it, but why not.

>Here's the instructions to enable CLA checking for fsnotify.  You can do it either at the organization level, in which case it will apply to all repos in the org, or just to the individual repos you want it activated for.  The same webhook secret will work in either case.

>1. Give googlebot write access to the repos.  Adding as an outside collaborator is fine, or you can add the account to the org if you don't want to setup each repo individually.  Up to you.  Write access is needed in order to set commit statuses and issue labels.

>2. If you want googlebot to set issue labels, go ahead and create the labels "cla: yes" and "cla: no".  If you don't care about the labels, and will just check for the commit status, then just don't create them and googlebot won't try to add them.

>3. Add a new webhook to the org or repo:

>Payload URL: https://cla.developers.google.com/api/github/webhook
>Content type: application/json
>Secret: [elided, ask]
>Which events would you like to trigger this webhook?
>Select "Let me select individual events" and then select only "Issue comment" and "Pull Request".
>Active: this should be checked

>That should be it.

>Most of the time it should go pretty smoothly.  The one edge case that we don't handle well is when someone is submitting a PR containing commits that they did not author themselves.  In that case, the comment from googlebot should hopefully explain the situation pretty well.  It's a case where we rely on a human being (you) to do a little bit of legwork and go ahead and merge the commit, even though the official status from googlebot says that things aren't okay.  I've got a feature request outstanding to try and handle this case better.

**Comment by arp242** [comment]
I'm not sure if we still need to do anything here.

Reading through the various issues, the only advantage would be that fsnotify could potentially be integrated in the stdlib or a golang.org/x/ package. I think it's fairly safe to say that a "os/fsnotify" package will never happen; the trend has been to move away from large/complex packages in stdlib in favour of either golang.org/x/… or community-maintained packages such as this. "Stdlib is where good code goes to die" and all of that. golang.org/x/… might happen, but I don't think that's especially likely either.

Looking at some of the go.mod files in e.g. x/tools, it seems like the lack of a CLA isn't preventing golang.org/x packages from potentially using this:

https://github.com/golang/pkgsite/blob/master/go.mod
https://github.com/golang/tools/blob/master/go.mod
https://github.com/golang/tools/blob/master/gopls/go.mod
https://github.com/golang/website/blob/master/go.mod

Before the only option was to vendor code, but now we have modules which seems to have solved the problem and the need for a CLA here.

---

More pragmatically, we haven't tracked who did and didn't sign a CLA for close to ten years now, so someone would have to check everyone and probably track some people down. The list isn't that large, but I don't really feel like doing it; I enjoy writing code and I don't enjoy badgering people to sign a document. That's work, not a hobby. Similarly, I don't really feel like setting up CLA bots, pinging people to sign the thing, deal with people who don't want to sign it because $reasons, and whatnot. If there was a serious advantage to all of that then okay, let's put in the work, but as far as I can see the advantage would be minimal at best now.
