### ISSUE TITLE
Can't read events from /dev/bus

### ISSUE THREAD

**Issue by Nhoya** [fsnotify/fsnotify#197]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: Debian Jessie 8.7
### Please describe the issue that occurred.
adding a watcher on /dev/bus i'm unable to read events from it, otherwise inotify can

Inotify output
```
inotifywait -mr -e create -e delete /dev/bus
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/dev/bus/usb/003/ DELETE 069
/dev/bus/usb/003/ CREATE 070
```

**Comment by arp242** [comment]
You set up the watcher on `/dev/bus`, but the path that gets modified is `/dev/bus/usb/003/`. Your `inotifywait` command has `-r` for recursive watches, but this isn't supported in fsnotify (yet, WIP in #472).

If I use `fsnotify /dev/bus/usb` I get the same events as `inotifywait`.

Closing as it's not really related to watching /dev or /dev/bus, but due to the lack of a recursive watcher (#18, #472).
