### ISSUE TITLE
Don't follow symlinks

### ISSUE THREAD

**Issue by mprobst** [fsnotify/fsnotify#199]
### Which operating system (GOOS) and version are you using?

LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty

### Please describe the issue that occurred.

fsnotify follows symlinks before watching, which makes it impossible to get notified of the symlink itself being modified. Specifically, fsnotify does not set `IN_DONT_FOLLOW` [here](https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L99). See [docs on IN_DONT_FOLLOW](https://linux.die.net/man/7/inotify).

As a user, I have no recourse for this. If fsnotify did not follow symlinks, I could follow the symlink myself before watching, but as is I cannot watch symlinks at all.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

`watcher.Add("some/symlink")`, then e.g. re-point the symlink itself (not its target!).

**Comment by mvdan** [comment]
This is limiting my use of fsnotify too. This would make for a rather simple patch - care to submit a patch, @mprobst?

I don't see a reason to always follow symlinks. If anyone wishes to do so, they can just use `filepath.EvalSymlinks` which is explicit.

**Comment by Code0x58** [comment]
I don't know how portable avoiding the dereferncing would be, but if doable I think it would be a great improvement to the interface by giving what feels like a nice and tidy ~low level abstraction over the various watchers.

_Waffle continuing on a separation between low+high level:_

A high level interface built on this could be nice too. I'm thinking it would watch any symlinks that lead some end file, and the end file itself.

Here is an example of files/links and how I imagine the handling:
```
/a/link (to /b/link)
/b/link (to /c/link)
/c/link (to /file)
/file
/d/link (to /other-file)
/other-file
```
`watch("/a/link")` should watch (`/a/link`, `/b/link`, `/c/link`, `/file`)
 1. `/b/link` changes to a a non-sysmlink, then drop the watches for (`/c/link`, `/file`). Report a change to `/a/link`
 2. `/b/link` changes to a link again to `/file`, add a watch for `/file` to the list . Report a change to `/a/link`
 3. `/file` is updated. Report a change to `/a/link`
 4. `/file` is changed to a link to `/d/link`, add a watch to `/d/link` and `/other-file`. Report a change to `/a/link`

I think any implementation of this high level interface would have some caveats around state changing between the time of the notification and the possibility of changes happening to files before the processing occurs, so getting it done as well as possible and documented in one place would be nice. I'm thinking there may also be issues with portability with regards to renaming.

I'll try to have a read through the design doc and more of the project and it's competition.

_P.S. I found this issue after following an issue for https://github.com/banzaicloud/bank-vaults which uses this and wants to watch config file which is commonly a link to a link to a file due to using a projection in kubernetes._

**Comment by nathany** [comment]
This sounds like a good idea.

We do need to decide if we want to consider it a breaking API change, taking us to v2.0. And if so, whether we want to hold off on this until we fix some bugs in 1.x and/or do some other breaking changes for v2.0.

**Comment by Code0x58** [comment]
This may be doable as a non-breaking change by updating #289 :
 1. rename `watcher.Add` to `watcher.AddRaw`
 2. reimplement `watcher.Add` with something like:
```go
func (w *Watcher) Add(name string) error {
    rawPath, err := filepath.EvaluateSymlinks(name)
    if err != nil {
        return fmt.Errorf("error resolving %#v: %s", name, err)
    }
    err = w.AddRaw(rawPath)
    if err != nil {
        if name != rawPath {
            return fmt.Errorf("error adding %#v for %#v: %s", rawPath, name, err)
        } else {
            return err
        }
    }
    return nil
}
```
 3. reinstate the removed `TestFsnotifyFakeSymlink` and `TestCyclicSymlink` tests (they continue to use `watcher.Add`) - at this time I'm not sure if this would reveal more work

**Comment by Code0x58** [comment]
I just pushed another commit on top of #289 so the functionality is available through a new method rather than changing the existing public interface

**Comment by jayunit100** [comment]
hi folks ! any update on this ? in kubernetes, this links back to an issue where when we change configmaps, we don't automatically signal containers to restart , so it would be cool to get this in :)

**Comment by Code0x58** [comment]
As of [v1.5.0](https://github.com/fsnotify/fsnotify/releases/tag/v1.5.0) (just released), there is `AddRaw(...)` which does not dereference symlinks, so covers this issue.
