### ISSUE TITLE
Are events from sysfs possible, and should we add them to this?

### ISSUE THREAD

**Issue by purpleidea** [fsnotify/fsnotify#242]
Are events from sysfs possible, and should we add them to this?

**Comment by ast** [comment]
fsnotify on Linux uses inotify as backend. inotify is not designed to work with sysfs.
epoll and poll and maybe also select works well with sysfs. fsnotify would have to use epoll instead of inotify, perhaps by making backend selectable but this would break API I guess? Is it worth it?

You can access epoll/poll https://godoc.org/golang.org/x/sys/unix

Example:
https://gist.github.com/ast/c410d90a814aa5af879974f312bbafe3

**Comment by purpleidea** [comment]
@ast Thank you very much for the example! I guess based on your reasoning I should close this.

Cheers!

**Comment by ast** [comment]
Here's a somewhat more complete example with a similar api to fsnotify
https://gist.github.com/ast/a41816345e94e065890440e87e41a219
