### ISSUE TITLE
file permission affect file watch notification

### ISSUE THREAD

**Issue by YoghurtFree** [fsnotify/fsnotify#366]
HI

I am adding some code to watch a file in Debian. Whenever I write to a file, based on the permission I get different notifications. the issue is almost the same to [issue](https://github.com/fsnotify/fsnotify/issues/110#issue-125535270)

the file permissions are:
-rw-r--r-- 1 root root 3689 May 10 17:39 /etc/ncarzone/config/frontend/app-config.json

Notifications received : RENAME, CHMOD, REMOVE (I don't get any write notification) :(

uname -a
Linux  3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 GNU/Linux

cat /etc/os-release:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

package :
"github.com/fsnotify/fsnotify"

**Comment by nathany** [comment]
Sorry, I don't have any insight to add to this right now.

**Comment by arp242** [comment]
This issue seems identical to #110 that you mentioned? Some parts even seem copy/pasted from that issue? 🤔 I'll close this for now as it seems identical to #110.

Aside: Linux 3.10 is a kernel from 2013, and Debian 10 shipped with Linux 4.19. The `el7` in your uname seems to hint you're running RedHat or something based on that (e.g. CentOS), rather than Debian.
