### ISSUE TITLE
Receiving WRITE events after a REMOVE event

### ISSUE THREAD

**Issue by suroh1994** [fsnotify/fsnotify#384]
### Which operating system (GOOS) and version are you using?
Windows: 10 Pro

### Please describe the issue that occurred.
I noticed when I delete a directory on Windows, the watcher received a REMOVE event for each child of that directory, then a REMOVE event for the directory, followed by WRITE event for each child. Is this correct behaviour? 

Also how would I remove watchers for deleted directories? I tried removing them in response to the remove event, but it gave me a "file does not exist" error. I read in #238 that fsnotify will take care of this, but I don't know if that has been implemented or not and the comment specifically said there are issues with Windows.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.
Create a watcher for a directory with at least one file in it. Delete the directory and watch the event output.

**Comment by arp242** [comment]
This is the expected behaviour; all backends behave like this.

I don't think there's any way we can improve on that, even if we wanted to. And I'd argue it's also the correct behaviour: if you're watching a directory and interested in changes to a particular file, then getting just a REMOVE for the directory would be quite surprising.

**Comment by arp242** [comment]
Sorry, part of my comment got lost; "REMOVE event for each child of that directory, then a REMOVE event for the directory" is expected; "followed by WRITE event for each child" is not something I can reproduce.

For the commands:

	C:\Users\martin\fsnotify\test>date /t > one
	C:\Users\martin\fsnotify\test>date /t > two
	C:\Users\martin\fsnotify\test>date /t > three
	C:\Users\martin\fsnotify\test>del three
	C:\Users\martin\fsnotify\test>cd ..
	C:\Users\martin\fsnotify>rmdir /s /q test

This is what I currently get (with the commands added):

	C:\Users\martin\fsnotify>go run ./cmd/fsnotify ./test
	18:76:03.8166 watching; press ^C to exit

	Creating the files
		18:76:24.0252   1 CREATE                "test\\one"
		18:76:24.0281   2 WRITE      (modified) "test\\one"
		18:76:26.4286   3 CREATE                "test\\two"
		18:76:26.4318   4 WRITE      (modified) "test\\two"
		18:76:27.7929   5 CREATE                "test\\three"
		18:76:27.8062   6 WRITE      (modified) "test\\three"

	Removing three
		18:76:43.2725   7 REMOVE                "test\\three"

	Removing the dir
		18:76:13.5079   8 REMOVE                "test\\one"
		18:76:13.5086   9 REMOVE                "test\\two"
		18:76:13.5098  10 REMOVE                "test"

I don't see any WRITE events.

So that part needs more information and a reproducible test case. This particular case is also tested in the CI (and has been for a long time).

**Comment by suroh1994** [comment]
Hi arp242, thanks for the reply. It's been a while since I encountered this issue and I don't recall what I did to cause it. If I do encounter this issue again, I'll get back to you. But thanks for the clear reply!
