### ISSUE TITLE
Getting duplicate watcher events for a single write operation on a file

### ISSUE THREAD

**Issue by mahigadamsetty** [fsnotify/fsnotify#501]
**Describe the bug**
On windows 10 machine I have a GO program which uses fsnotify to watch for changes for a .txt file. When I added some text in it and save the file, I was expecting I would get only one write event notification but I have seen two duplicate notifications.

GO program
`watcher, err := fsnotify.NewWatcher()
	if err != nil {
		panic(err)
	}
	doneChan := make(chan struct{})
	defer watcher.Close()

	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	if err := watcher.Add("temp.txt"); err != nil {
		panic(err)
	}
	<-doneChan`

Terminal Output
`go run main.go
2022/09/04 01:26:00 event: "temp.txt": WRITE
2022/09/04 01:26:00 event: "temp.txt": WRITE`

**To Reproduce**
Run the program which I have pasted above and  add some text in .txt file and save

**Expected behavior**
Expected only one notification for a single write operation

**Which operating system and version are you using?**
Windows: 10 

**Additional context**
If applicable, add screenshots or a code sample to help explain your problem.

**Comment by arp242** [comment]
It's not guaranteed that you'll only receive a single write event, and a single "write" can show up as multiple writes either because you're actually *doing* multiple writes (e.g. truncate + write) or just because that's what the platform sends.

How exactly this can be best handled depends a bit on your use case, but the general strategy to deal with this is to wait a short time for more write events, resetting the wait period for every new event. There is a little example over here: https://github.com/fsnotify/fsnotify/blob/main/cmd/fsnotify/dedup.go (note it won't compile with the latest tagged version, so you'll have to use the main branch or rewrite the `Has()` methods).
