### ISSUE TITLE
Rename, and re-Add doesn't work

### ISSUE THREAD

**Issue by baryluk** [fsnotify/fsnotify#503]
```
watcher.Add("foo")
// mv foo bar  //  (RENAME event is generated)
watcher.Add("foo")
// write to "foo"
// no events for "foo"
```

**Which operating system and version are you using?**
Linux: 6.0.0-rc4

**Comment by arp242** [comment]
If I watch `file`, rename it to `rename`, re-watch `file`, and write to both `rename` and `file` I get these events:

	rename    /file  # mv file rename
	write     /file  # cat hello >>rename
	write            # cat hello >>file

The path missing from that last event is clearly incorrect. On Windows it makes a bit more sense:

	rename /file    # mv file rename
	write  /rename  # cat hello >>rename
	write  /file    # cat hello >>file

kqueue drops the watch on renames:

	rename   /file    # mv file rename
	write    /file    # cat hello >>file

---

The problem is that watches "survive" renames on Linux and that the file path isn't updated. This isn't even necessarily *wrong* and may even be expected in some situations. I'm a bit hesitant to "just" change it because it may break things.

There are a bunch of different ways this can be handled. I'm tempted to just leave it as-is and clean it all up and properly define the expected behaviour in v2. Other broken/inconsistent behaviours such as symlinks on kqueue has previously broken people's programs.
