### ISSUE TITLE
TestInotifyNoBlockingSyscalls fail on arm

### ISSUE THREAD

**Issue by zhsj** [fsnotify/fsnotify#531]
**To Reproduce**
`GOARCH=arm go test ./...`

```
--- FAIL: TestInotifyNoBlockingSyscalls (6.02s)
    inotify_test.go:400: Got a nonzero diff 2. starting: 12. ending: 14
FAIL
```

**Expected behavior**
Not error

**Which operating system and version are you using?**

Linux: lsb_release -a

```
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        n/a
Codename:       bookworm
```

**Comment by zhsj** [comment]
The above is running with qemu-user-static on my amd64 machine.

Another example that running armel on an arm64 machine.

https://ci.debian.net/data/autopkgtest/testing/armel/g/golang-fsnotify/27757621/log.gz

**Comment by arp242** [comment]
Can you restart that autopkgtest? I think this test is just a bit flaky and occasionally fails.

**Comment by arp242** [comment]
Also, where can I see the test builds for 1.6.0? They don't show up at https://ci.debian.net/packages/g/golang-fsnotify/ (?)

**Comment by zhsj** [comment]
https://ci.debian.net/packages/g/golang-fsnotify/testing/armel/ The first column is the version, and I have triggered it some times.

**Comment by arp242** [comment]
> https://ci.debian.net/packages/g/golang-fsnotify/testing/armel/ The first column is the version, and I have triggered it some times.

Ah thanks. How do you get there from https://ci.debian.net/packages/g/golang-fsnotify/ though? 🤔 

At any rate, this test checks if no additional OS threads are created; this was added after the old epoll-based inotify code was removed (which would create additional threads). It's always been a bit flaky: it currently already runs the test twice and "fails" only if both fail.

We don't really control the Go scheduler and when it creates/destroys OS threads, or have all that much insight in it (the "threadcreate" profile in pprof has been broken for years). I tried to make this test a bit more reliable a few months ago, and the run-it-twice "solution" was the best I could come up.

I'm not sure if this test adds all that much value; I don't really foresee a regression where we accidentally create more OS threads than we should; I'm tempted to just remove this test. 

Either way: it should be safe to just ignore. I don't know why it consistently fails on armle (and not e.g. arm64), but that seems a Go thing, rather than a fsnotify thing.

CC @horahoradev

**Comment by zhsj** [comment]
> Ah thanks. How do you get there from https://ci.debian.net/packages/g/golang-fsnotify/ though? thinking

The web UI is not good to understand...

> Either way: it should be safe to just ignore. I don't know why it consistently fails on armle (and not e.g. arm64), but that seems a Go thing, rather than a fsnotify thing.

Good to know, thanks.

**Comment by horahoradev** [comment]
> > https://ci.debian.net/packages/g/golang-fsnotify/testing/armel/ The first column is the version, and I have triggered it some times.
> 
> Ah thanks. How do you get there from https://ci.debian.net/packages/g/golang-fsnotify/ though? 🤔
> 
> At any rate, this test checks if no additional OS threads are created; this was added after the old epoll-based inotify code was removed (which would create additional threads). It's always been a bit flaky: it currently already runs the test twice and "fails" only if both fail.
> 
> We don't really control the Go scheduler and when it creates/destroys OS threads, or have all that much insight in it (the "threadcreate" profile in pprof has been broken for years). I tried to make this test a bit more reliable a few months ago, and the run-it-twice "solution" was the best I could come up.
> 
> I'm not sure if this test adds all that much value; I don't really foresee a regression where we accidentally create more OS threads than we should; I'm tempted to just remove this test.
> 
> Either way: it should be safe to just ignore. I don't know why it consistently fails on armle (and not e.g. arm64), but that seems a Go thing, rather than a fsnotify thing.
> 
> CC @horahoradev
whoops, sorry I missed your reply. I don't think it's especially meaningful to ensure that there's a zero diff in threads before and after running readEvents many times. As long as we're not creating a ton of new threads (e.g. >10?), we should be good. Otherwise, this test's success is at the mercy of the Go runtime. As you said though, regression is unlikely, so we can probably just remove the test.
