### ISSUE TITLE
can it find the process, which create the file?

### ISSUE THREAD

**Issue by b1gcat** [fsnotify/fsnotify#564]
Can it find the process, which cause the file changed?

**Comment by kolyshkin** [comment]
This is not a support forum.

**Comment by arp242** [comment]
I'm okay with using the issue tracker for questions (I didn't keep up with notifications for the last few weeks, so I'm only seeing this now).

To answer this question: no, this isn't supported, because most platorms don't provide a facility for this. Perhaps something Linux-specific can be added once fanotify support is merged, but that will be platform-specific and only work on Linux.
