### ISSUE TITLE
Support for intermediary multiplexer like watchman

### ISSUE THREAD

**Issue by jeremie-stripe** [fsnotify/fsnotify#599]
👋 

It's sometimes beneficial when we deal with large amount of files and multiple processes needing to watch those files to resort to a multiplexer like watchman (https://github.com/facebook/watchman) to avoid starving OS resources (the multiplexer will take care of merging multiple similar requests from each process to a single set of, say, inotify handles).

I'm interested to see if there is a way to offer such a "backend" to fsnotify and how the API would allow it (as right now it seems fairly static, one platform = one backend) and how we would want to allow passing extra initialization data (for instance watchman will, at least, request a root folder to start subscribing to file changes).

Is this something fsnotify would philosophically want to provide or is it better in a higher layer/other library?

**Comment by jeremie-stripe** [comment]
For context, equivalent to fsnotify in other ecosystem sometimes do provide both form of backend (what I would call native and multiplexer). An example would be [parcel-watcher](https://github.com/parcel-bundler/watcher).

**Comment by arp242** [comment]
This sounds like something that should be a layer on top of this – fsnotify really just abstracts the OS APIs. As I rule I'd say if it can be implemented somewhere else without large performance or complexity costs, then it should be implemented somewhere else, and I think that's the case here?

That said, I don't necessarily mind including it as a subpackage, provided it's not too complex.

**Comment by jeremie-stripe** [comment]
The main appeal of providing it in-library to me is that it should be a somewhat simple change for consumers to start using it and guarantees the API is the same (otherwise the burden is on the consumers to maintain their own two backends, fsnotify and whatever the other thing is).

To be more concrete, one target we are thinking of is [ibazel](https://github.com/bazelbuild/bazel-watcher/tree/master/internal/ibazel/fswatcher) where, instead of making it a dependency there, it seems like it could be more straightforward to add the watchman support in the lower layer of fsnotify (but that's only a hunch). 

When you suggest a sub-package, what kind of architecture do you envision and would it relate to the main fsnotify library?

**Comment by arp242** [comment]
This seems useful for very few use-cases; I don't think we need to go out of our way for this.

> When you suggest a sub-package, what kind of architecture do you envision and would it relate to the main fsnotify library?

I don't really know; I don't really have a clear view on the requirements or what would and wouldn't work well.

**Comment by arp242** [comment]
I slept on this, and I feel this should first be developed/prototyped outside of fsnotify as its own package, and then *maybe* depending on how complex it all is we can consider integrating it here, based on a real-world implementation. 

I can't give you a firm yes/no on whether it will be integrated here, which is not helpful, but it's the best I can do without actually having something concrete. Maybe the implementation turns out to be quite simple, or maybe it's quite subtle and complex – I'm not really sure, and the only way to really answer that is to have a concrete implementation.

If integrating an externally developed solution turns out to be difficult then that's probably a signal it's too complex to be added here.

Of course, if there's something in fsnotify that prevents you from developing something like that, then that's something that should be addressed.

Other than that: just do whatever you think makes sense. I'm not that fussy about specific designs, and a working implementation can always be changed. My main concern is just added complexity and maintenance burden, for something that seems useful but also useful for only a tiny percentage of use cases.
