### ISSUE TITLE
short read in readEvents on Windows

### ISSUE THREAD

**Issue by bbigras** [fsnotify/fsnotify#72]
I have some `watcher.Errors: short read in readEvents()` once every couple of minutes.

I'm not able to reproduce the problem if I run the smallest code possible to watch the same directory.

What should I try next to reproduce the `short read` error?

go version go1.4.2 windows/386

**Comment by nathany** [comment]
That error would be coming from here: https://github.com/go-fsnotify/fsnotify/blob/master/windows.go#L448

Unfortunately I don't know the Windows code very well yet. It was inherited from Chris Howey's version of fsnotify, which was inherited from [winfsnotify](https://github.com/golang/exp/tree/master/winfsnotify).

If you manage to add enough to a code example to reproduce the issue, that would really help.

**Comment by rubenhazelaar** [comment]
I have a similar problem (Windows 8.1), running golang 1.5.2 and the latest go-fsnotify (from gopkg.in/fsnotify.v1). When I place a lot of files (200+) in my directory I get the following:

```
2016/02/10 15:08:31 error: short read in readEvents()
2016/02/10 15:08:35 error: short read in readEvents()
2016/02/10 15:08:37 error: short read in readEvents()
2016/02/10 15:08:40 error: short read in readEvents()
2016/02/10 15:08:43 error: short read in readEvents()
2016/02/10 15:08:46 error: short read in readEvents()
2016/02/10 15:08:49 error: short read in readEvents()
2016/02/10 15:08:51 error: short read in readEvents()
2016/02/10 15:08:58 EOF
```

When EOF is put out, the executable crashes. Could this be something like a buffer overflow?

**Comment by nathany** [comment]
Sorry, I'm still not really sure. :disappointed:

**Comment by rubenhazelaar** [comment]
I did some testing. The EOF was caused by a xml decoder I use, so solved that one.

However the short read error remains. 

In my setup I use ftp to upload a bunch of files. The problem also occurs when I just copy the files in the folder. When a create event is fired (it fires twice btw, don't know if this is normal) I decode the content of each file and put that content in a db. So quite heavy work. Could this be interfering with fsnotify's ability to process all the new files? Or perhaps because it's a lot to process the os takes a different route which throws off fsnotify or the underlying API? Just speculating btw :)

**Comment by rubenhazelaar** [comment]
Ok, had the opportunity to test on a Linux machine and had a weird difference:

On Windows the WRITE event is fired **3x**, in Linux (ElementaryOS) **1x**

When a short read error occurs (on Windows) it seems to truncate the file it is reading (not necessarily always the case, seems to happen sometimes). This is also why my XML decoder errored with EOF.

I just use a normal directory. To trigger the WRITE event I just copy the files to the watched folder. Hop it helps, if you need any other info please let me know.

**Comment by nathany** [comment]
Thanks for the info. I'm not sure when I (or someone else) will have a chance to dig into the Windows code for fsnotify to figure out what's going on. But any details to help reproduce it are helpful.

**Comment by cobolbaby** [comment]
+1

**Comment by nathany** [comment]
See also https://github.com/howeyc/fsnotify/issues/122

**Comment by nicks** [comment]
we were able to fix this by making the windows i/o buffer dynamically adjustable, as in https://github.com/tilt-dev/fsnotify/pull/5

**Comment by cobolbaby** [comment]
@nicks the bug is finally solved.

**Comment by mauricioharley** [comment]
This bug is not fully fixed.  I'm facing the exact behavior with Windows 10 while using Go 1.17.2.  Any news so far?

**Comment by fengyach** [comment]
I encountered the same issue with GO 1.16. Windows Server 2012 R2.

**Comment by nicks** [comment]
@gnoack I think this issue sums up the current merge queue / mainenance situation - https://github.com/fsnotify/fsnotify/issues/413

**Comment by arp242** [comment]
> @gnoack I think this issue sums up the current merge queue / mainenance situation - https://github.com/fsnotify/fsnotify/issues/413

It's now maintained again @nicks!

I looked at your patch in https://github.com/tilt-dev/fsnotify/pull/5, but it doesn't really "dynamically" adjust the buffer size: people will have to call `SetBufferSize()`, which is fine for a "quick fix" but not ideal, especially since it'll only be available on Windows (e.g. in tilt you [need to use build tags](https://github.com/tilt-dev/tilt/blob/c4f96ac6e2bfc861881e26c56375c2b2dfc3af64/internal/watch/watcher_windows.go) to actually call it).

It would be better to increase the buffer size as needed; the windows code is a bit messy, but I'm sure this has got to be possible.

Do you want to work on a patch for this?

Also: I wonder if we can't just double the buffer size to 8K or 16K or something, which should at least make things a bit better. It looks like tilt uses a whopping [8M by default](https://github.com/tilt-dev/tilt/blob/77ae37f8f66c4b2d6df5eb526bd71954be73ecf2/internal/watch/notify.go#L75), which is probably fine for a "heavy" application like tilt, but seems a bit much for the general use case.
