### ISSUE TITLE
Miss events when use mv to overwrite the file

### ISSUE THREAD

**Issue by wangjild** [fsnotify/fsnotify#80]
``` go

package main

import (
    "github.com/go-fsnotify/fsnotify"
    "log"
)

func main() {
    watcher, err := fsnotify.NewWatcher()
    if err != nil {
        panic(err)
    }

    defer watcher.Close()

    done := make(chan bool)

    go func() {
        for {
            select {
            case event := <-watcher.Events:
                log.Println("event:", event)
                if event.Op&fsnotify.Write == fsnotify.Write {
                    log.Println("modified file:", event.Name)
                }
            case err := <-watcher.Errors:
                log.Println("error:", err)
            }
        }
    }()

    if err = watcher.Add("./conf/"); err != nil {
        panic(err)
    }

    <-done
}
```

I use "mv" to overwrite the origin file, but got only "REMOVE" status, and the use echo "" >> to append some content, but got nothing!

My platform is OS X

![6587009f-ccb0-4db8-8d35-6e52011849eb](https://cloud.githubusercontent.com/assets/1264866/8395653/440288ea-1db0-11e5-8cdb-ba24bcd5f041.png)

**Comment by wangjild** [comment]
the file I used by mv is a empty file.

It seems the system emit a "Write" event to the "conf" directory and then secondly send a "remove" event to the conf/test.yml file.

**Comment by nathany** [comment]
Hi Wang Jing,
This looks unusual. Was there a test.yml file there before? When a REMOVE event happens, it stops watching that file, but I haven't yet looked into this scenario where the file is overwritten.

**Comment by wangjild** [comment]
Sorry, I forgot to tell you.   there was a test.yml in the conf directory.

I have readed the code,  it seems the kqueue returned a WRITE event to the "conf" firstly, and then a REMOVE event to the "conf/test.yml".

This is very strange. The same test code returned "CREATE" events in linux platform. This is just what I expected.

When a file is overwrite by "cp" or "mv", CREATE events is more helpful than REMOVE, at lease I could use this event to reload the "test.yml". But if it returned REMOVE, I could not determine whether the "test.yml" is deleted by "rm" or overwrited by "cp" or "mv"

**Comment by nathany** [comment]
The events from the underlying system are largely unmodified, resulting in differences from one platform to the next.

I'm not sure what the best solution is right now. I don't know if it will always be possible to present the same result across 4-5 platforms.

**Comment by anthonyfok** [comment]
Hi @nathany,

I think what you said earlier, i.e. "When a REMOVE event happens, it stops watching that file", hits the nail right on the head.

I ran into the same problem, on Linux, while trying out Hugo v0.15's new "dynamically reload config file" feature.  While editors like GNU nano triggers the WRITE event, other editors like Vim and GNOME gedit first save the changes to a temporary file, then moving the tempfile to replace the original file, triggering a REMOVE event before a CREATE or WRITE event, but the CREATE or WRITE event was never detected because the watcher quits prematurely!

Please see spf13/viper#142 for more details.

If that is the case, I don't think this bug is "OS X (kqueue)"-specific.  Rather, if the "When a REMOVE event happens, it stops watching that file" behaviour is "as-designed", perhaps that design needs to be changed.

Many thanks for looking into this.

**Comment by nathany** [comment]
One solution would be not support watching individual files at all. I think that might be the approach that https://godoc.org/github.com/rjeczalik/notify takes. FSEvents on OS X also seems geared towards watching directories instead of files. 

Of course, if a directory is (re)moved, you may still have to watch one level up to see what happened.

**Comment by arp242** [comment]
With these commands:

	[/tmp/test]% touch file
	[/tmp/test]% mv file x
	[/tmp/test]% touch ../outside
	[/tmp/test]% mv ../outside .
	[/tmp/test]% print test >> outside
	[/tmp/test]% mv outside outside-rename
	[/tmp/test]% touch ../outside
	[/tmp/test]% mv ../outside .

I get the following events:

	[~/fsnotify]% go run ./cmd/fsnotify /tmp/test
	00:86:30.7567 watching; press ^C to exit
	00:86:53.5287   1 CREATE                "/tmp/test/file"
	00:86:56.5230   2 CREATE                "/tmp/test/x"
	00:86:56.5231   3 RENAME                "/tmp/test/file"
	00:86:06.1362   4 CREATE                "/tmp/test/outside"
	00:86:06.3935   5 WRITE      (modified) "/tmp/test/outside"
	00:86:23.8367   6 CREATE                "/tmp/test/outside-rename"
	00:86:23.8369   7 RENAME                "/tmp/test/outside"
	00:86:27.6006   8 CREATE                "/tmp/test/outside"

Which seems alright to me.

I tested this on both macOS and FreeBSD, which behave identical.

Since this is an old issue that I can't reproduce, I'll close this for now; please get back to me if you're still experiencing it and we can reopen and investigate further.
