### ISSUE TITLE
No way to see if an Event.Name is for a file or directory without a stat

### ISSUE THREAD

**Issue by guotie** [fsnotify/fsnotify#81]
I think dir events and file events should not use the same event, so who use the lib have to judge the event is on a dir or is or file

**Comment by nathany** [comment]
Maybe there should be a flag indicating if the event is a dir or file event?

**Comment by infogulch** [comment]
Perhaps add a `Dir` Op constant?

**Comment by nathany** [comment]
That would be nice. The question is whether we can add that across each platform without introducing additional overhead (Lstat when not needed).

**Comment by omeid** [comment]
Lstat when 'Event.Dir()' is called.

**Comment by arp242** [comment]
We can't really add this in a cross-platform way; kqueue for starters doesn't really support it.

I'm hesitant to call Lstat() because it's subject to race conditions: the path may have gone away once you get around calling it (so it won't work for Remove() events, but also if a write is closely followed by a remove, or worse, a file may get replaced by a directory or the other way around). Besides, it's not much shorter or easier than just calling Lstat() yourself if you need it, and the potential caveats with that will be a lot clearer than when it's "hidden" by a Dir() call.

Once #67 is implemented, you can use that for platforms that support it, such as inotify.
